name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Before filling a bug report it would be great to [upgrade](https://docs.victoriametrics.com/victorialogs/#upgrading)
        to [the latest available release](https://docs.victoriametrics.com/victorialogs/changelog/)
        and verify whether the bug is reproducible there.
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
      placeholder: |
        When I do `A` VictoriaMetrics does `B`. I expect it to do `C`.
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior.
        If reproducing an issue requires some specific configuration file, please paste it here.
      placeholder: |
        Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: |
        The line returned when passing `--version` command line flag to the binary. For example:
        ```
        $ ./victoria-logs-prod --version
        victoria-logs-v1.24.0
        ```
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Check if any warnings or errors were logged by VictoriaLogs components
        or components in communication with VictoriaLogs (e.g. log collectors and shippers, Grafana, etc.).
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
  
        For VictoriaLogs health-state issues please provide full-length screenshots
        of Grafana dashboards if possible:
          * [Grafana dashboard for single-node VictoriaLogs](https://grafana.com/grafana/dashboards/22084)
          * [Grafana dashboard for VictoriaLogs cluster](https://grafana.com/grafana/dashboards/23274)
        
        See [how to setup monitoring](https://docs.victoriametrics.com/victorialogs/#monitoring)
    validations:
      required: false
  - type: textarea
    id: flags
    attributes:
      label: Used command-line flags
      description: |
        Please provide the command-line flags used for running VictoriaLogs and its components.
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      placeholder: |
        Additional information that doesn't fit elsewhere
    validations:
      required: false
