name: Question
description: Ask a question regarding VictoriaLogs or its components
labels: [question]
body:
  - type: textarea
    id: describe-the-component
    attributes:
      label: Is your question request related to a specific component?
      placeholder: |
        VictoriaLogs, vlagent, vlogscli, built-in web UI, Grafana plugin, etc...
    validations:
      required: false
  - type: textarea
    id: describe-the-question
    attributes:
      label: Describe the question in detail
      description: |
        A clear and concise description of the issue and the question.
    validations:
      required: true
  - type: checkboxes
    id: keyconcepts
    attributes:
      label: Key concepts docs
      description: I am familiar with the following docs
      options:
        - label: VictoriaLogs key conepts - https://docs.victoriametrics.com/victorialogs/keyconcepts/
          required: false
        - label: LogsQL - https://docs.victoriametrics.com/victorialogs/logsql/
          required: false
